{
 "title": "Containers",
 "tags": [ "workshop" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU per container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (container_name) (container_cpu_utilization_ratio{container_name!=\"\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory per container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (container_name) (container_memory_usage_total_bytes{container_name!=\"\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory now",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(max by (container_name) (container_memory_usage_total_bytes{container_name!=\"\"}))",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}